#pragma config(Motor,  port2,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int forwards;
int backwards;
int nada;

void liftControl (int leftLift, int rightLift)
{
	motor[leftArm] = leftLift;
	motor[rightArm] = rightLift;
}

void baseControl (int leftSide, int rightSide)
{
	motor[leftSideDrive] = leftSide;
	motor[rightSideDrive] = rightSide;
}

task main()
{
forwards = 127;
backwards = -127;
nada = 0;

while(1 == 1)
{
	if(vexRT[Btn5U] == 1)
	{
}
}
