#pragma config(Motor,  port2,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void liftControl (int leftLift, int rightLift)
{
	motor[leftArm] = leftLift;
	motor[rightArm] = rightLift;
}


// If button up (StartTask Mogo up & Stop Task MogoDown)
// If bottom down (StartTask Mogo Down & Stop Task MogoUp
//


task main()
{

	while(1==1)
	{
		motor[leftSideDrive] = vexRT[Ch3];
		motor[rightSideDrive] = vexRT[Ch2];

		if(vexRT[Btn6U] == 1)
		{
			liftControl(-127, -127);
		}
		else if(vexRT[Btn6D] == 1)
		{
			liftControl(127, 127,);
		}
		else
		{
			liftControl(0, 0);
		}
		if(vexRT[Btn6D] == 1)
		{
			liftControl(127, 127);
		}
		else if(vexRT[Btn6U] == 1)
		{
			liftControl(-127, -127);
		}
		else
		{
			liftControl(0, 0);
		}
	}
}
