#pragma config(Motor,  port2,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftTurntable, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightTurntable, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void liftControl(int leftSide, int rightSide)
{
	motor[leftTurntable] = leftSide;
	motor[rightTurntable] = rightSide;

}
task main()
{

	while(1==1)
	{
			motor[leftSideDrive] = vexRT[Ch3];
			motor[rightSideDrive] = vexRT[Ch2];
			//map joysticks to motors, left drive is on the left stick vertical axis, right drive on right stick vertical axis

			if(vexRT[Btn6U] == 1)
				{
					motor[intake] = -127;
				}
			else if(vexRT[Btn6D] == 1)
				{
					motor[intake] = 127;
				}
			else
				{
					motor[intake] = 0;
				}

			//if button 6U is pressed, move intake backwards
			//if button 6D is pressed, move intake forwards
			//if neither, then do nothing

			if(vexRT[Btn6D] == 1)
				{
					motor[intake] = 127;
				}
			else if(vexRT[Btn6U] == 1)
				{
					motor[intake] = -127;
				}
			else
				{
					motor[intake] = 0;
				}

			//if button 6D is pressed, move intake backwards
			//if button 6U is pressed, move intake forwards
			//if neither, then do nothing

			//Partner Control Section begins here

			motor[leftArm] = vexRT[Ch3Xmtr2];
			motor[rightArm] = vexRT[Ch2Xmtr2];
			//mapping joysticks to turntables

			if(vexRT[Btn6UXmtr2] == 1)
			{
				liftControl(-127, -127);
			}
			else if(vexRT[Btn6DXmtr2] == 1)
			{
				liftControl(127, 127);
			}
			else
			{
				liftControl(0, 0);
			}
			//if button 6UXmtr2 is pressed, bring lift up
			//if button 6DXmtr2 is pressed, bring lift down
			//if neither, then do nothing


			if(vexRT[Btn6DXmtr2] == 1)
			{
				liftControl(127, 127);
			}
			else if(vexRT[Btn6UXmtr2] == 1)
			{
				liftControl(-127, -127);
			}
			else
			{
				liftControl(0, 0);
			}

			//if button 6DXmtr2 is pressed, bring lift down
			//if button 6UXmtr2 is pressed, bring lift up
			//if neither, then do nothing

		}
	}
