#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mobileGoalMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightSideLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           gripMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftSideLift,  tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	int forwards;
	int backwards;
	int nada;

	forwards = 127;
	backwards = -127;
	nada = 0;
	clearTimer(T1);
	while(time1[T1] < 15000)
	{
		motor[rightSideDrive] = forwards;
		motor[leftSideDrive] = forwards;
		wait1Msec(1000);
		//go forwards for 1 second
		motor[rightSideDrive] = nada;
		motor[leftSideDrive] = nada;
		wait1Msec(1000);
		//stop movement for one second
		motor[rightSideLift] = forwards;
		motor[leftSideLift] = forwards;
		wait1Msec(1000);
		//move arm upwards (may have to add in grip motor)
		motor[rightSideLift] = 0;
		motor[leftSideLift] = 0;
		wait1Msec(1000);
		//stop the lift at the top
		motor[gripMotor] = backwards;
		wait1Msec(1000);
		//claw releases cone
		//might have to move robot backwards a tiny bit so it can pick up mobile goal
		motor[rightSideLift] = backwards;
		motor[leftSideLift] = backwards;
		wait1Msec(1000);
		//move arm down
		motor[rightSideLift] = nada;
		motor[leftSideLift] = nada;
		wait1Msec(1000);
		//stops arm movement at bottom
		//insert code for robot to drive up to mobile cone
		motor[gripMotor] = forwards;
		wait1Msec(1000);
		//robot grabs mobile goal, might have to do w/ code when robot moves forwards
		motor[leftSideDrive] = nada;
		motor[rightSideDrive] = nada;
		wait1Msec(1000);
		//stops movement of robot
		motor[rightSideDrive] = forwards;
		motor[leftSideDrive] = backwards;
		wait1Msec(500);
		//robot turns to the left for half of a second (fine tune so it goes 180 degrees
		motor[rightSideDrive] = nada;
		motor[leftSideDrive] = nada;
		wait1Msec(1000);
		//robot stops movement
		motor[rightSideDrive] = forwards;
		motor[leftSideDrive] = forwards;
		wait1Msec(2000);
		//robot moves forwards into 10 pt zone (gotta fine tune)
		motor[rightSideDrive] = nada;
		motor{leftSideDrive] = nada;
		wait1Msec(500);
		//robot stops moving
		motor[gripMotor] = backwards;
		wait1Msec(1000);
		//robot claw releases the mobile goal lift
		motor[gripMotor] = nada;
		wait1Msec(100);
		//robot claw closes again
		motor[rightSideDrive] = backwards;
		motor[leftSideDrive] = forwards;
		wait1Msec(1000);
		//robot turns around for a second (fine tune to 180 degrees)
		motor[rightSideDrive] = nada;
		motor[leftSideDrive] = nada;
		wait1Msec(500);
		//robot stops movement
	}
}
		/*
		//turn
		motor[rightSideDrive] = forwards;
		motor[leftSideDrive] = backwards;
		wait1Msec(200);
		motor[rightSideDrive] = nada;
		motor[leftSideDrive] = nada;

		//drive forwards
		motor[rightSideDrive] = forwards;
		motor[leftSideDrive] = forwards;
		wait1Msec(2000);
		motor[rightSideDrive] = nada;
		motor[leftSideDrive] = nada;

		//arm up
		motor[rightSideLift] = 90;
		motor[leftSideLift] = 90;
		wait1Msec(200);
		motor[rightSideLift] = nada;
		motor[leftSideLift] = nada;

		//drive forwards
		//arm down
		motor[rightSideLift] = -90;
		motor[leftSideLift] = -90;
		wait1Msec(200);
		motor[rightSideLift] = nada;
		motor[leftSideLift] = nada;

		//grab
		motor[gripMotor] = 90;
		wait1Msec(400);
		motor[gripMotor] = 0;

		//turn left
		//drive forwards
		//arm up
		motor[rightSideLift] = 90;
		motor[leftSideLift] = 90;
		wait1Msec(200);
		motor[rightSideLift] = nada;
		motor[leftSideLift] = nada;

		//drive forwards
		//arm down
		motor[rightSideLift] = -90;
		motor[leftSideLift] = -90;
		wait1Msec(200);
		motor[rightSideLift] = nada;
		motor[leftSideLift] = nada;

		//release
		motor[gripMotor] = -90;
		wait1Msec(400);
		motor[gripMotor] = 0;
	}
}
*/

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	int forwards;
	int backwards;
	int nada;

	forwards = 95;
	backwards = -95;
	nada = 0;
	while (true)
	{
		motor[rightSideDrive] = vexRT[Ch2];
		motor[leftSideDrive] = vexRT[Ch3];
		/*if(vexRT[Btn6U] == 1)
		{
			motor[rightSideLift] = forwards;
			motor[leftSideLift] = forwards;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[rightSideLift] = backwards;
			motor[leftSideLift] = backwards;
		}
		else
		{
			motor[rightSideLift] = nada;
			motor[leftSideLift] = nada;
		}
		*/
		motor[rightSideLift] = vexRT[Ch2Xmtr2];
		motor[leftSideLift] = vexRT[Ch2Xmtr2];
		if(vexRT[Btn5U] == 1)
		{
			motor[gripMotor] = forwards;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[gripMotor] = backwards;
		}
		else
		{
			motor[gripMotor] = nada;
		}
	}
}
