#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mobileGoalMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftLift,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Copyright Noah Schonhorn, 2017
task main()
{
	int forward;
	int backward;
	int nada;

	forward = 127;
	backward = -127;
	nada = 0;
	//Above integers are values for moving the motors forward at full power, backwards at full power, and stopped.

		while(1 == 1)
		{
			motor[rightSideDrive] = vexRT[Ch2];
			motor[leftSideDrive] = vexRT[Ch3];
			//Left Drive controlled by Left Joystick, Right Drive controlled by Right Stick.
				if(vexRT[Btn6U] == 1)
				{
					motor[rightLift] = forward;
					motor[leftLift] = forward;
				}
				else if(vexRT[Btn6D] == 1)
				{
					motor[rightLift] = backward;
					motor[leftLift] = backward;
				}
				else
				{
					motor[rightLift] = nada;
					motor[leftLift] = nada;
					//Right triggers control up and down movement for the lift.
				}
				if(vexRT[Btn5U] == 1)
				{
					motor[clawMotor] = 127;
				}
				else if(vexRT[Btn5D] == 1)
				{
					motor[clawMotor] = -127;
				}
				else
				{
					motor[clawMotor] = nada;
					//Left triggers control movement of the claw motor.
				}
				if(vexRT[Btn8L] == 1)
				{
					motor[mobileGoalMotor] = forward;
				}
				else if(vexRT[Btn8D] == 1)
				{
					motor[mobileGoalMotor] = backward;
				}
				else
				{
					motor[mobileGoalMotor] = nada;
					//Right D-Pad buttons control movement of the mobile goal motor (Y and B, L and D, X and A.)
				}
			}
}
