#pragma config(Motor,  port2,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoalMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int forward;
	int backward;
	int nada;

	forward = 127;
	backward = -127;
	nada = 0;

	motor[rightSideDrive] = forward;
	motor[leftSideDrive] = backward;
	wait1Msec(15000);

		while(1 == 1)
		{
			motor[rightSideDrive] = vexRT[Ch2];
			motor[leftSideDrive] = vexRT[Ch3];

				if(vexRT[Btn6U] == 1)
				{
					motor[rightLift] = forward;
					motor[leftLift] = forward;
				}
				else if(vexRT[Btn6D] == 1)
				{
					motor[rightLift] = backward;
					motor[leftLift] = backward;
				}
				else
				{
					motor[rightLift] = nada;
					motor[leftLift] = nada;
				}
				if(vexRT[Btn5U] == 1)
				{
					motor[clawMotor] = forward;
				}
				else if(vexRT[Btn5U] == 1)
				{
					motor[clawMotor] = backward;
				}
				else
				{
					motor[clawMotor] = nada;
				}
				if(vexRT[Btn8L] == 1)
				{
					motor[mobileGoalMotor] = forward;
				}
				else if(vexRT[Btn8D] == 1)
				{
					motor[mobileGoalMotor] = backward;
				}
				else
				{
					motor[mobileGoalMotor] = nada;
				}
			}
}
