#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[port2] = 127;
	wait1Msec(1000);
	motor[port3] = 127;
	wait1Msec(1000);
	motor[port4] = 127;
	wait1Msec(1000);
	motor[port5] = 127;
	wait1Msec(1000);
	motor[port6] = 127;
	wait1Msec(1000);
	motor[port7] = 127;
	wait1Msec(1000);
	motor[port8] = 127;
	wait1Msec(1000);
	motor[port9] = 127;
	wait1Msec(1000);


}
