#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int masterpower;
	int slavepower;
	int error;
	int kp;
	int forwards;


	masterpower = 127;
	slavepower = 127;
	error = 0;
	kp = 5;
	forwards = 127;

	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(true)
	{
		motor[rightMotor] = masterpower;
		motor(leftMotor) = slavepower;

		error = SensorValue[leftEncoder] - SensorValue[rightEncoder];

		slavepower += error / kp;

		SensorValue[leftEncoder] = 0;
		SensorValue[rightEncoder] = 0;

		wait1Msec(100);

	}



}
