#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightLift,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int downborder = 256;
	int upborder = 512;
	while(1 == 1)
		{
		if(vexRT[Btn6U] == 1 && SensorValue[pot] <= upborder)
		{
			motor[leftLift] = 60;
			motor[rightLift] = 60;
		}
		else if(vexRT[Btn6U] == 1 && SensorValue[pot] > upborder)
		{
			motor[leftLift] = 0;
			motor[rightLift] = 0;
		}
		else if(vexRT[Btn6U] == 0)
		{
			motor[leftLift] = 0;
			mot or[rightLift] = 0;
		}
		if(vexRT[Btn6D] == 1 && SensorValue[pot] >= downborder)
		{
			motor[leftLift] = -60;
			motor[rightLift] = -60;
		}
		else if(vexRT[Btn6D] == 1 && SensorValue[pot] < downborder)
		{
			motor[leftLift] = 0;
			motor[rightLift] = 0;
		}
		else if(vexRT[Btn6D] == 0)
		{
			motor[leftLift] = 0;
			motor[rightLift] = 0;
		}
	}
}
