#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

motor(rightMotor) = 127;
motor(leftMotor) = 127;
wait1Msec(1000);


}
