#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in5,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, in6,    CenterLine,     sensorLineFollower)
#pragma config(Sensor, in7,    RightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mainLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           turntableMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           gripMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftExtension, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task Battery()
{
bLCDBacklight = true;
string mainBattery, backupBattery;

while(true)
{
	clearLCDLine(0);
	clearLCDLine(1);

	//display

	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	displayLCDString(1, 0, "Backup:  ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0,'V');
	displayNextLCDString(backupBattery);

	wait1Msec(100);
}
}

void baseControl(int leftPower, int rightPower)
{
	motor[leftSideDrive] = leftPower;
	motor[rightSideDrive] = rightPower;
}

void liftControl (int leftLift, int rightLift)
{
	motor[leftMobileGoal] = leftLift;
	motor[rightMobileGoal] = rightLift;
}


	task Straighten()
{

int difference;
int leftStart;
int rightStart;


leftStart = 101;
rightStart = 83;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;


	while(1 == 1)
	{
		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			baseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			baseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			baseControl((leftStart - difference), rightStart);
		}
	}
}

task BackStraighten()
{
float difference;
float leftStart;
float rightStart;


leftStart = -57.5;
rightStart = -47.5;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;

	while(1 == 1)
	{

		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			baseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			baseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			baseControl((leftStart - difference), rightStart);
		}
	}
}

task BackStraightenFast()
{
float difference;
float leftStart;
float rightStart;


leftStart = -101;
rightStart = -95;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;

	while(1 == 1)
	{

		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			baseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			baseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			baseControl((leftStart - difference), rightStart);
		}
	}
}

task autonomous()
{
	{
	liftControl (127, 127);
	wait1Msec(750);
	//bring out mobile goal

	liftControl (0, 0);
	wait1Msec(100);
	//stop

		startTask(Straighten);
	baseControl (127, 127);
	wait1Msec(1900);
	stopTask(Straighten);
	//drive to mobile goal

	baseControl (0,0);
	wait1Msec(250);
	//stop

	motor[rightMobileGoal] = -100;
	motor[leftMobileGoal] = -100;
	wait1Msec(600);
	//mobile goal grabs cone

	motor[rightMobileGoal] = 0;
	motor[leftMobileGoal] = 0;
	wait1Msec(100);
	//stop

	startTask(BackStraighten);
	baseControl (-127, -127);
	wait1Msec(1750);
	//back up

	baseControl (-127, -127);
  untilLight (2951, in6);
  stopTask(BackStraighten);
	//back up to line

	baseControl(-100, -25);
	wait1Msec(1250);
	//first pivot

	baseControl(0, 0);
	wait1Msec(100);
	//quick stop

	baseControl(-50, 50);
wait1Msec(600);
//2nd pivot

baseControl(0, 0);
wait1Msec(200);
//quick stop

startTask(Straighten);
baseControl(60, 60);
wait1Msec(1450);
stopTask(Straighten);
//drive to 20 pt

baseControl(0, 0);
wait1Msec(100);
//stops

liftControl(90, 90);
wait1Msec(75);
//places mobile goal in 20pt zone

liftControl(0, 0);
wait1Msec(50);
//stop lift

liftControl(-90, -90);
wait1Msec(75);
//pull out

liftControl(0, 0);
wait1Msec(50);
//stop lift

baseControl(0, 0);
wait1Msec(100);
//stop

startTask(BackStraightenFast);
baseControl(-127, -127);
wait1Msec(1000);
//back up


baseControl(-127, -127);
untilDark(2951, in6);
stopTask(BackStraightenFast);
//back up straight out of 20pt zone

baseControl(0, 0);
liftControl(0, 0);
wait1Msec(100);
//stop

	}
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	while(1==1)
	{
		motor[leftSideDrive] = vexRT[Ch3];
		motor[rightSideDrive] = vexRT[Ch2];

		if(vexRT[Btn8U] ==1)
		{
			stopTask(Battery);
			startTask(Battery);
			wait1Msec(100);
		}

		if(vexRT[Btn6U] == 1 )
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
	}

	if(vexRT[Btn6U] == 1 )
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}

		if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal]= 127;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else
		{
			motor[leftMobileGoal] = 0;
			motor[rightMobileGoal] = 0;
		}


	{
		if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
	}

	{
		if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
	}
	}
