#pragma config(Motor,  port2,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rampTipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           leftTurntable, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightTurntable, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[leftSideDrive] = 0;
	motor[rightSideDrive] = 0;
	wait1Msec(10000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


void liftControl(int liftPower)
{
	motor[leftTurntable] = liftPower;
	motor[rightTurntable] = liftPower;

}

void armControl(int armPower)
{
	motor[leftArm] = armPower;
	motor[rightArm] = armPower;
}

void intakeControl(int intakePower)
{
	motor[intake] = intakePower;
}

task usercontrol()
{

	while(1==1)
	{
			motor[leftSideDrive] = vexRT[Ch3];
			motor[rightSideDrive] = vexRT[Ch2];
			//map joysticks to motors, left drive is on the left stick vertical axis, right drive on right stick vertical axis

			if(vexRT[Btn6U] == 1)
				{
					intakeControl(127);
				}
			else if(vexRT[Btn6D] == 1)
				{
					intakeControl(-127);
				}
			else

				{
					intakeControl(0);
				}

			//if button 6U is pressed, move intake backwards
			//if button 6D is pressed, move intake forwards
			//if neither, then do nothing

			if(vexRT[Btn6D] == 1)
				{
					intakeControl(-127);
				}
			else
				{
					intakeControl(0);
				}

			//if button 6D is pressed, move intake backwards
			//if button 6U is pressed, move intake forwards
			//if neither, then do nothing




				if(vexRT[Btn7D] == 1)
				{
					motor[rampTipper] = -127;
				}
				else if(vexRT[Btn7R] == 1)
				{
					motor[rampTipper] = 127;
				}
				else
				{
					motor[rampTipper] = 0;
				}

			//Partner Control Section begins here

			if(vexRT[Btn6DXmtr2] == 1)
				{
					armControl( 75 );
				}
			else if(vexRT[Btn6UXmtr2] == 1)
				{
					armControl( -75 );
				}
			else
				{
					armControl( 0 );
				}


			//mapping joysticks to turntables

			if(vexRT[Btn5UXmtr2] == 1)
				{
				liftControl(-127);
				}
			else if(vexRT[Btn5DXmtr2] == 1)
				{
					liftControl(127);
				}
			else
				{
					liftControl(0);
				}
			//if button 6UXmtr2 is pressed, bring lift up
			//if button 6DXmtr2 is pressed, bring lift down
			//if neither, then do nothing
		}
	}
