#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in5,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, in6,    CenterLine,     sensorLineFollower)
#pragma config(Sensor, in7,    RightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mainLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           turntableMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           gripMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftExtension, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void baseControl(int leftPower, int rightPower)
{
	motor[leftSideDrive] = leftPower;
	motor[rightSideDrive] = rightPower;
}

void liftControl (int leftLift, int rightLift)
{
	motor[leftMobileGoal] = leftLift;
	motor[rightMobileGoal] = rightLift;
}

task Straighten
{
	int RightValue;
	int LeftValue;
	int difference;

	RightValue = SensorValue[RightEncoder];
	LeftValue = SensorValue[LeftEncoder];
	difference = (SensorValue[RightEncoder] - SensorValue[LeftEncoder]);

	if(difference > 0)
	{
		motor[rightSideDrive] = (127 - 10);
		motor[leftSideDrive] = 88;
	}

	if(difference < 0)
	{
		motor[leftSideDrive] = (88-10);
		motor[rightSideDrive] = 127;
	}

	if(difference == 0)
	{
		motor[leftSideDrive] = 88;
		motor[rightSideDrive] = 127;
	}

}
task armAngle
{
	int angle;

	angle = SensorValue(RightPotentiometer);

	if(angle >= 1150)
	{
		liftControl (0, 0);
		wait1Msec(100);
	}
}
task main()
{
liftControl (127, 127) ;
	wait1Msec(700);
	//bring out mobile goal

	liftControl (0, 0);
	wait1Msec(100);
	//stop

	baseControl (90.225, 127);
	wait1Msec(2200);
	//drive to mobile goal

	baseControl (0,0);
	wait1Msec(250);
	//stop

	liftControl (-127, -127);
	wait1Msec(625);
	//mobile goal grabs cone

	liftControl (0 , 0);
	wait1Msec(100);
	//stop

	baseControl (-50, -35);
	wait1Msec(1500);
	//back up

	baseControl (0, 0);
	wait1Msec(100);
	//stop

	baseControl(-100, -25);
	wait1Msec(1250);
	//first pivot

	baseControl(0, 0);
	wait1Msec(100);
	//quick stop

	baseControl(-50, 50);
wait1Msec(700);
//2nd pivot

baseControl(0, 0);
wait1Msec(200);
//quick stop

baseControl(123, 127);
wait1Msec(2000);
//drive to 20 pt

baseControl(-127, -127);
wait1Msec(1000);
//reverse

baseControl(0, 0);
liftControl(0, 0);
wait1Msec(500);
//stop




}
