#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in5,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, in6,    CenterLine,     sensorLineFollower)
#pragma config(Sensor, in7,    RightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mainLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           turntableMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           gripMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftExtension, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Battery()
{
bLCDBacklight = true;
string mainBattery, backupBattery;

while(true)
{
	clearLCDLine(0);
	clearLCDLine(1);

	//display

	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	displayLCDString(1, 0, "Backup:  ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0,'V');
	displayNextLCDString(backupBattery);

	wait1Msec(100);
}
}

void baseControl(int leftPower, int rightPower)
{
	motor[leftSideDrive] = leftPower;
	motor[rightSideDrive] = rightPower;
}

void liftControl (int leftLift, int rightLift)
{
	motor[leftMobileGoal] = leftLift;
	motor[rightMobileGoal] = rightLift;
}


	task Straighten()
{

int difference;
int leftStart;
int rightStart;


leftStart = 101;
rightStart = 83;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;


	while(1 == 1)
	{
		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			baseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			baseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			baseControl((leftStart - difference), rightStart);
		}
	}
}

task BackStraighten()
{
float difference;
float leftStart;
float rightStart;


leftStart = -57.5;
rightStart = -47.5;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;

	while(1 == 1)
	{

		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			baseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			baseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			baseControl((leftStart - difference), rightStart);
		}
	}
}

task BackStraightenFast()
{
float difference;
float leftStart;
float rightStart;


leftStart = -101;
rightStart = -95;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;

	while(1 == 1)
	{

		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			baseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			baseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			baseControl((leftStart - difference), rightStart);
		}
	}
}


task main()
{
	while(1 == 1)
	{
			{
		motor[leftSideDrive] = vexRT[Ch3];
		motor[rightSideDrive] = vexRT[Ch2];

		if(vexRT[Btn6U] == 1 )
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
	}

	if(vexRT[Btn6U] == 1 )
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}

		if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal]= 127;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else
		{
			motor[leftMobileGoal] = 0;
			motor[rightMobileGoal] = 0;
		}


	{
		if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
	}

	{
		if(vexRT[Btn6D] == 1)
		{
			motor[rightMobileGoal] = 127;
			motor[leftMobileGoal] = 127;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[rightMobileGoal] = -127;
			motor[leftMobileGoal] = -127;
		}
		else
		{
			motor[rightMobileGoal] = 0;
			motor[leftMobileGoal] = 0;
		}
	}

if(vexRT(Btn8L) == 1)
{
	liftControl(0, 0);
	baseControl(0, 0);
}
	if(vexRT(Btn8U) == 1)
	{
	stopTask(Battery);
	wait1Msec(500);
	startTask(Battery);
}
	if(vexRT(Btn8R) == 1)
{
	liftControl (127, 127);
	wait1Msec(750);
	//bring out mobile goal

	liftControl (0, 0);
	wait1Msec(100);
	//stop

		startTask(Straighten);
	baseControl (127, 127);
	wait1Msec(1900);
	stopTask(Straighten);
	//drive to mobile goal

	baseControl (0,0);
	wait1Msec(250);
	//stop

	motor[rightMobileGoal] = -100;
	motor[leftMobileGoal] = -100;
	wait1Msec(600);
	//mobile goal grabs cone

	motor[rightMobileGoal] = 0;
	motor[leftMobileGoal] = 0;
	wait1Msec(100);
	//stop

	startTask(BackStraighten);
	baseControl (-127, -127);
	wait1Msec(1750);
	//back up

	baseControl (-127, -127);
  untilLight (2951, in6);
  stopTask(BackStraighten);
	//back up to line

	baseControl(-100, -25);
	wait1Msec(1250);
	//first pivot

	baseControl(0, 0);
	wait1Msec(100);
	//quick stop

	baseControl(-50, 50);
wait1Msec(600);
//2nd pivot

baseControl(0, 0);
wait1Msec(200);
//quick stop

startTask(Straighten);
baseControl(60, 60);
wait1Msec(1450);
stopTask(Straighten);
//drive to 20 pt

baseControl(0, 0);
wait1Msec(100);
//stops

liftControl(90, 90);
wait1Msec(75);
//places mobile goal in 20pt zone

liftControl(0, 0);
wait1Msec(50);
//stop lift

liftControl(-90, -90);
wait1Msec(75);
//pull out

liftControl(0, 0);
wait1Msec(50);
//stop lift

baseControl(0, 0);
wait1Msec(100);
//stop

startTask(BackStraightenFast);
baseControl(-127, -127);
wait1Msec(1000);
//back up


baseControl(-127, -127);
untilDark(2951, in6);
stopTask(BackStraightenFast);
//back up straight out of 20pt zone

baseControl(0, 0);
liftControl(0, 0);
wait1Msec(100);
//stop

	startTask(Straighten);
	baseControl(127, 127);
	wait1Msec(150);
	stopTask(Straighten);
	//forwards straighten


	baseControl(0, 0);
	wait1Msec(100);
	//stop

	baseControl(-100, 127);
	wait1Msec(380);
	//face wall (PIVOT)

	startTask(BackStraighten);
	baseControl(-127, -127);
	wait1Msec(2500);
	stopTask(BackStraighten);

	baseControl(-127, -95);
	wait1Msec(300);

	baseControl(0, 0);
	wait1Msec(100);

		liftControl (127, 127);
	wait1Msec(750);
	//bring out mobile goal

	liftControl (0, 0);
	wait1Msec(100);
	//stop

		startTask(Straighten);
		baseControl(50, 50);
		wait1Msec(1200);
		stopTask(Straighten);
		//drive to cone

		baseControl(0, 0);
		wait1Msec(100);
		//stop

		motor[rightMobileGoal] = -100;
	motor[leftMobileGoal] = -100;
	wait1Msec(600);
	//mobile goal grabs cone

	motor[rightMobileGoal] = 0;
	motor[leftMobileGoal] = 0;
	wait1Msec(100);
	//stop

	baseControl(50, -50);
	wait1Msec(1275);
	//face 10pt zone (PIVOT!!)

	baseControl(0, 0);
	wait1Msec(100);
	//stop

	startTask(Straighten);
	baseControl(50, 50);
	wait1Msec(1450);
	stopTask(Straighten);
	//drive to 10

	baseControl(0, 0);
	wait1Msec(100);
	//stop

	liftControl(-127, -127);
	wait1Msec(500);
	//drop mobile goal

	liftControl(0, 0);
	wait1Msec(100);
	//stop

	baseControl(-127, -127);
	untilLight(2885, in7);
	//back up to line

	baseControl(0, 0);
	wait1Msec(100);
	//stop

	baseControl(-101, 83);
	wait1Msec(750);
	//180 turn

	baseControl(0, 0);
	wait1Msec(100);
	//stop
}


}
}
