#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task Battery()
{
bLCDBacklight = true;
string mainBattery, backupBattery;

while(true)
{
	clearLCDLine(0);
	clearLCDLine(1);

	//display

	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	displayLCDString(1, 0, "Backup:  ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0,'V');
	displayNextLCDString(backupBattery);

	wait1Msec(100);
}
}

int reverseStatus = 0;

task Forwards()
{
	while(1==1)
	{
	motor[leftSideDrive] = vexRT[Ch3];
	motor[rightSideDrive] = vexRT[Ch2];
	reverseStatus = 0;
	}
}

task Reverse()
{
		while(1==1)
		{
		stopTask(Forwards);
		motor[leftSideDrive] = -vexRT[Ch3];
		motor[rightSideDrive] = -vexRT[Ch2];
		reverseStatus = 1;
	}
}
task main()
{
	while(1==1)
		{

			startTask(Forwards);



			if(vexRT[Btn8U] == 1)
			{
				stopTask(Reverse);
				startTask(Forwards);
			}
			if(vexRT[Btn8D] == 1)
			{
			if(reverseStatus == 1)
			{
				startTask(Forwards);
			}
			else
			{
				startTask(Reverse);
			}

			if(vexRT[Btn6U] == 1)
			{
				motor[clawMotor] = 127;
			}

		}
	}
}
