#pragma config(Sensor, in1,    LeftPotentiometer, sensorNone)
#pragma config(Sensor, in2,    GyroSensor,     sensorGyro)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in5,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, in6,    CenterLine,     sensorLineFollower)
#pragma config(Sensor, in7,    RightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  greenLed,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mainLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           turntableMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           gripMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftExtension, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Clears the gyro sensor readings.
	SensorType[GyroSensor] = sensorNone;
	wait1Msec(1000);
	//Reconfigure the gyro sensor to actually be a gyro sensor, allow time to calibrate
	SensorType[GyroSensor] = sensorGyro;
	wait1Msec(2000);
	//Number of degrees for the robot to turn.
	int degrees10 = 900;
	while(abs(SensorValue[GyroSensor]) < degrees10)
	{
		SensorValue[greenLed] = true;
	}
}
