#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTipper,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftTipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "getlcdbuttons.c"

static int MyAutonomous = 0;

void
LcdSetAutonomous( int value )
{
	if( value == 0 )
	{
		displayLCDString(0, 0, "Ten Point + Tip");
		displayLCDString(1, 0, "[00]   01    02 ");
	}
	if( value == 1 )
	{
		displayLCDString(0, 0, "Twenty Point");
		displayLCDString(1, 0, " 00   [01]   02 ");
	}
	if( value == 2 )
	{
		displayLCDString(0, 0, "Stay Still");
		displayLCDString(1, 0, " 00    01   [02]");
	}

	MyAutonomous = value;
}

void
LcdAutonomousSelection()
{
	TControllerButtons button;

	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;

	LcdSetAutonomous(0);

	while( bIfiRobotDisabled )
	{
		button = getLcdButtons();

		if( button == kButtonLeft )
			LcdSetAutonomous(0);

		if ( button == kButtonCenter )
			LcdSetAutonomous(1);

		if( button == kButtonRight )
			LcdSetAutonomous(2);

		wait1Msec(10);
	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;

	LcdAutonomousSelection();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void driveControlA(int rightDrive, int leftDrive)
{
	motor[leftSideDrive] = leftDrive;
	motor[rightSideDrive] = rightDrive;
}
void mogoControlA(int rightMogo, int leftMogo)
{
	motor[leftMobileGoal] = leftMogo;
	motor[rightMobileGoal] = rightMogo;
}
void tipperControlA(int rightTip, int leftTip)
{
	motor[leftTipper] = leftTip;
	motor[rightTipper] = rightTip;
	//nice
}

task autonomous()
{
	switch( MyAutonomous )
	{
	case 0:
		//auton code 1 here
		driveControlA(127, 127);
		wait1Msec(3000);

		mogoControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(500);

		mogoControlA(127, 127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(1000);

		driveControlA(127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(1000);

		mogoControlA(-127, -127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, -127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(500);

		tipperControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(1000);
		break;

	case 1:
		//auton code 2 here
		break;

	default:
		driveControlA(0, 0);
		mogoControlA(0, 0);
		tipperControlA(0, 0);
		wait1Msec(15000);
		break;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void mogoControlR(int rightMogo, int leftMogo)
{
	motor[leftMobileGoal] = leftMogo;
	motor[rightMobileGoal] = rightMogo;
}
void tipperControlR(int rightTip, int leftTip)
{
	motor[leftTipper] = leftTip;
	motor[rightTipper] = rightTip;
	//nice
}

task usercontrol()
{

	while(1==1)
	{
		motor[leftSideDrive] = vexRT[Ch3];
		motor[rightSideDrive] = vexRT[Ch2];

		if(vexRT[Btn6U] == 1)
		{
			mogoControlR(-127, -127);
		}
		else if(vexRT[Btn6D] == 1)
		{
			mogoControlR(127, 127);
		}
		else
		{
			mogoControlR(0, 0);
		}
		if(vexRT[Btn5D] == 1)
		{
			tipperControlR(-127, -127);
		}
		else if(vexRT[Btn5U] == 1)
		{
			tipperControlR(127, 127);
		}
		else
		{
			tipperControlR(0, 0);
		}
	}
}
