#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in4,    gyroSensor,     sensorGyro)
#pragma config(Sensor, dgtl1,  touchSensor,     sensorTouch)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTipper,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftTipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "getlcdbuttons.c"

static int MyAutonomous = 0;

//Autonomous Selection

#define MAX_CHOICE 7

void
LcdAutonomousSet( int value, bool select = false )
{
	clearLCDLine(0);
	clearLCDLine(1);

	displayLCDString(1, 0, l_arr_str);
	displayLCDString(1, 13, r_arr_str);

	if(select)
		MyAutonomous = value;

	if( MyAutonomous == value )
		displayLCDString(1, 5, "ACTIVE");
	else
		displayLCDString(1, 5, "Select");

	switch(value)
	{
	case 0:
		displayLCDString(0, 0, "Ten Point + Tip");
		break;
	case 1:
		displayLCDString(0, 0, "Regular Ten Point");
		break;
	case 2:
		displayLCDString(0, 0, "Zero Point Auto");
		break;
	case 3:
		displayLCDString(0, 0, "Battery Test");
		break;
	case 4:
		displayLCDString(0, 0, "Defensive");
		break;
	case 5:
		displayLCDString(0, 0, "Double tip");
		break;
	case 6:
		displayLCDString(0, 0, "RCon (no comp)");
	case 7:
		displayLCDString(0, 0, "Single Tip ;)");
	default:
		displayLCDString(0, 0, "Unknown");
		break;
	}
}

//Cycle through different autonomous choices

void
LcdAutonomousSelection()
{
	TControllerButtons button;
	int choice = 0;

	bLCDBacklight = true;

	LcdAutonomousSet(0);

	while( bIfiRobotDisabled )
	{
		button = getLcdButtons();

		if( ( button == kButtonLeft ) || ( button == kButtonRight ) )
		{
			if( button == kButtonLeft )
				if( --choice < 0 ) choice = MAX_CHOICE;

			if( button == kButtonRight )
				if( ++choice > MAX_CHOICE ) choice = 0;
			LcdAutonomousSet(choice);
		}

		if( button == kButtonCenter )
			LcdAutonomousSet( choice, true );

		wait1Msec(10);
	}
}



/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;

	LcdAutonomousSelection();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
	task Battery()
{
bLCDBacklight = true;
string mainBattery, backupBattery;

while(true)
{
	clearLCDLine(0);
	clearLCDLine(1);

	//display

	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	displayLCDString(1, 0, "Backup:  ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0,'V');
	displayNextLCDString(backupBattery);

	wait1Msec(100);
	}
}

void PIDbaseControl (int speed)
{
		motor[leftSideDrive] = speed;
		motor[rightSideDrive] = speed;
}

void straightBaseControl (int leftSide, int rightSide)
{
	motor[leftSideDrive] = leftSide;
	motor[rightSideDrive] = rightSide;
}

void baseControl(int leftPower, int rightPower, int baseTime)
{
	motor[leftSideDrive] = leftPower;
	motor[rightSideDrive] = rightPower;
	baseTime = wait1Msec(baseTime);
}

void rawBaseControl(int leftSide, int rightSide)
{
	motor[leftSideDrive] = leftSide;
	motor[rightSideDrive] = rightSide;
}

void rawliftControl(int leftSideMogo, int rightSideMogo)
{
	motor[leftMobileGoal] = leftSideMogo;
	motor[rightMobileGoal] = rightSideMogo;
}
void liftControl (int leftLift, int rightLift, int liftTime)
{
	motor[leftMobileGoal] = leftLift;
	motor[rightMobileGoal] = rightLift;
	liftTime = wait1Msec(liftTime);
}

void tipControl (int leftTip, int rightTip, int tipTime)
{
	motor[rightTipper] = rightTip;
	motor[leftTipper]= leftTip;
	tipTime = wait1Msec(tipTime);
}

//reading: ticks -- 627.2ticks/revolution
// 1 turn of the wheels -- 4 inch wheels = 627.2 *2 ticks
//1 turn of each wheel 4*pi inches
//4*pi inches = 627.2*2 ticks

//ticks/inch = 627.2 * 2 /4*pi= 99.82198


int inchToTicks (float inch)
{
		int ticks;
		ticks = inch*99.82198;
		return ticks;
 }

int fixTimerValue (float rawSeconds)
{
	int miliseconds;
	miliseconds = rawSeconds*1000;
	if (miliseconds < 250)
	{
			miliseconds = 250;
	}
	return miliseconds;
}
void BaseControlPID (float target, float waitTime, float maxPower = 1)
{
		float Kp = 0.26;
		float Ki = 0.05;
		float Kd = 0.62;

		int RightSensor;
		int LeftSensor;

		RightSensor = SensorValue[RightEncoder]*-1;
		LeftSensor = SensorValue[LeftEncoder];

		int error;

		float proportion;
		int integralRaw;
		float integral;
		int lastError;
		int derivitave;

		float integralActiveZone = inchToTicks(3);


		int finalPower;

		bool timerBool = true;

		SensorValue(LeftEncoder) = 0;
		SensorValue(RightEncoder) = 0;


		clearTimer(T1);

		while(time1[T1] < fixTimerValue(waitTime))
		{
			error = inchToTicks(target/2) - (2*(SensorValue(LeftEncoder)));

			proportion = Kp*error;

			if (abs(error) < integralActiveZone && error != 0)
			{
				integralRaw = integralRaw+error;
			}
			else
			{
				integralRaw = 0;
			}

			integral = Ki*integralRaw;

			derivitave = Kd*(error-lastError);
		 	lastError = error;

		 	if (error == 0)
		 	{
		 			derivitave = 0;
			}

			finalPower = proportion+integral+derivitave; //proportion+derivitave + intergral

			if(finalPower > maxPower*127)
			{
				finalPower = maxPower*127;
			}
			else if(finalPower < -maxPower*127)
			{
				finalPower= -maxPower*127;
			}

			PIDbaseControl(finalPower);

			wait1Msec(40);

			if (error < 30)
			{
					timerBool = false;
			}

			if (timerBool)
			{
				clearTimer(T1);
			}
	}
	PIDbaseControl(0);
}

	task GyroReset()
	{
		//Completely clear out any previous sensor readings by setting the port to "sensorNone"
 SensorType[in4] = sensorNone;
 wait1Msec(1000);
 //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
 SensorType[in4] = sensorGyro;
 wait1Msec(2000);
}

	task PivotLeft100()
{
//Adjust SensorScale to correct the scaling for your gyro
SensorScale[in4] = 103.86;
 //Adjust SensorFullCount to set the "rollover" point. 3600 sets the rollover point to +/-3600
SensorFullCount[in4] = 3600;

//Specify the number of degrees for the robot to turn (1 degree = 10, or 900 = 90 degrees)
 int degrees100 = 1800;

//While the absolute value of the gyro is less than the desired rotation...
 while(abs(SensorValue[in4]) < degrees100)
 {
 //...continue turning
 motor[rightSideDrive] = 50;
 motor[leftSideDrive] = -50;
 }

//Brief brake to stop some drift
 motor[rightSideDrive] = -25;
 motor[leftSideDrive] = 25;
 wait1Msec(250);

 baseControl(0,0, 100);
 stopTask(PivotLeft100);
}

	task Straighten()
{

int difference;
int leftStart;
int rightStart;


leftStart = 100;
rightStart = 83;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;


	while(1 == 1)
	{
		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			straightBaseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			straightBaseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			straightBaseControl((leftStart - difference), rightStart);
		}
	}
}

task BackStraighten()
{
float difference;
float leftStart;
float rightStart;


leftStart = -57.5;
rightStart = -47.5;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;

	while(1 == 1)
	{

		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			straightBaseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			straightBaseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			straightBaseControl((leftStart - difference), rightStart);
		}
	}
}

task BackStraightenFast()
{
float difference;
float leftStart;
float rightStart;


leftStart = -101;
rightStart = -95;


SensorValue(RightEncoder) = 0;
SensorValue(LeftEncoder) = 0;

	while(1 == 1)
	{

		difference = abs(SensorValue(LeftEncoder) - SensorValue(RightEncoder))/1000;

		if(SensorValue(RightEncoder) == SensorValue(LeftEncoder))
		{
			straightBaseControl(leftStart, rightStart);
		}

		if(SensorValue(RightEncoder) > SensorValue(LeftEncoder))
		{
			straightBaseControl(leftStart, (rightStart - difference));
		}

		if(SensorValue(LeftEncoder) > SensorValue(RightEncoder))
		{
			straightBaseControl((leftStart - difference), rightStart);
		}
	}
}



task autonomous()
{
	switch( MyAutonomous )
	{
	case 0:
		//Ten Point + Tip

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(3000);
		stopTask(Straighten);

		mogoControl(-127, -127, 500);

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(500);
		stopTask(Straighten);

		mogoControl(127, 127);
		wait1Msec(500);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(1000);
		stopTask(BackStraightenFast);

		rawBaseControl(127, -127);
		wait1Msec(500);

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(1000);
		stopTask(Straighten);

		mogoControl(-127, -127);
		wait1Msec(500);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(500);
		stopTask(BackStraightenFast);

		rawBaseControl(127, -127);
		wait1Msec(500);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(500);
		stopTask(BackStraightenFast);

		tipperControl(-127, -127, 500);

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(1000);
		stopTask(Straighten);
		break;

	case 1:
		//Regular Ten Point
				startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(3000);
		stopTask(Straighten);

		mogoControl(-127, -127);
		wait1Msec(500);

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(500);
		stopTask(Straighten);

		mogoControl(127, 127);
		wait1Msec(500);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(1000);
		stopTask(BackStraightenFast);

		rawBaseControl(127, -127);
		wait1Msec(500);

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(1000);
		stopTask(Straighten);

		mogoControl(-127, -127);
		wait1Msec(500);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(500);
		stopTask(BackStraightenFast);

	case 2:
		//Stay Still, Zero Points
		rawBaseControl(0, 0);
		mogoControl(0, 0);
		tipperControl(0, 0);
		wait1Msec(15000);
		break;

	case 3:
		//Battery Test
		bLCDBacklight = true;
		string mainBattery, backupBattery;

		while(1==1)
		{
			clearLCDLine(0);
			clearLCDLine(1);
			//Primary battery voltage display
			displayLCDString(0, 0, "Primary: ");
			sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
			displayNextLCDString(mainBattery);
			//Backup battery voltage display
			displayLCDString(1, 0, "Backup: ");
			sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
			displayNextLCDString(backupBattery);
			wait1Msec(100);
		}
		break;

	case 4:
		//Defensive, straight backwards
		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(3000);
		stopTask(BackStraightenFast);
		break;

	case 5:
		//Double tip that sh*t
		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(3000);
		stopTask(Straighten);

		tipperControl(127, 127);
		wait1Msec(1000);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(1000);
		stopTask(BackStraightenFast);

		tipperControl(-127, -127);
		wait1Msec(1000);

		rawBaseControl(127, -127);
		wait1Msec(1000);

		startTask(Straighten);
		rawBaseControl(127, 127);
		wait1Msec(1000);
		stopTask(Straighten);

		tipperControl(127, 127);
		wait1Msec(1000);

		startTask(BackStraightenFast);
		rawBaseControl(-127, -127);
		wait1Msec(1000);
		stopTask(BackStraightenFast);

	case 6:
		//Drive testing, just in case
		while (true)
		{
			{
				motor[leftSideDrive] = vexRT[Ch3];
				motor[rightSideDrive] = vexRT[Ch2];

				if(vexRT[Btn6U] == 1)
				{
					mogoControl(-127, -127);
				}
				else if(vexRT[Btn6D] == 1)
				{
					mogoControl(127, 127);
				}
				else
				{
					mogoControl(0, 0);
				}
				if(vexRT[Btn5D] == 1)
				{
					tipperControl(-127, -127);
				}
				else if(vexRT[Btn5U] == 1)
				{
					tipperControl(127, 127);
				}
				else
				{
					tipperControl(0, 0);
				}
			}
			break:
			{

			case 7:


			startTask(BackStraightenFast);
			baseControl(-127, -127, 1250);
			stopTask(BackStraightenFast);
			baseControl(0, 0, 250);

			tipControl(120, 120, 1370);
			tipControl(0, 0, 0);
			//move tip up

			tipControl(60, 60, 500);
			BaseControlPID(30, 0, 1);

		}



		}
	}
}
}
break;
		}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void mogoControlR(int rightMogo, int leftMogo)
{
	motor[leftMobileGoal] = leftMogo;
	motor[rightMobileGoal] = rightMogo;
}
void tipperControlR(int rightTip, int leftTip)
{
	motor[leftTipper] = leftTip;
	motor[rightTipper] = rightTip;
	//nice
}

task usercontrol()
{


	while (true)
	{
		{
			motor[leftSideDrive] = vexRT[Ch3];
			motor[rightSideDrive] = vexRT[Ch2];

			if(vexRT[Btn6U] == 1)
			{
				mogoControlR(-127, -127);
			}
			else if(vexRT[Btn6D] == 1)
			{
				mogoControlR(127, 127);
			}
			else
			{
				mogoControlR(0, 0);
			}
			if(vexRT[Btn5U] == 1)
			{
				tipperControlR(-127, -127);
			}
			else if(vexRT[Btn5D] == 1)
			{
				tipperControlR(127, 127);
			}
			else
			{
				tipperControlR(0, 0);
			}
		}
	}
}
