#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTipper,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftTipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
int Program;
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	int lcdScreenMin = 1;
	int lcdScreen = 1;
	int lcdScreenMax = 3;
	bLCDBacklight = true;

	const short leftButton = 1;
	const short centerButton = 2;
	const short rightButton = 4;

	while(bIfiRobotDisabled == 1) //vrDisabled means that the vexNet key is not plugged in. Change later if this doesn't work.
	{
		if (nLCDButtons == leftButton) //Slide to the left
		{
			if (lcdScreenMin == lcdScreen)
			{
				lcdScreen = lcdScreenMax;
				wait1Msec(250);
			}
			else
			{
				lcdScreen --;
				wait1Msec(250);
			}
		}
		if (nLCDButtons == rightButton) //Slide to the right
		{
			if (lcdScreenMax == lcdScreen)
			{
				lcdScreen = lcdScreenMin;
				wait1Msec(250);
			}
			else
			{
				lcdScreen++;
				wait1Msec(250);
			}
		}
		if (lcdScreen == 1 && Program != 1)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "1");
			if (nLCDButtons == centerButton)
			{
				Program = lcdScreen;
				displayLCDCenteredString (0, "Ten Point + Tip");
				displayLCDCenteredString (1, "Auto Selected");
				wait1Msec(1500);
			}
		}
		else if (lcdScreen == 1 && Program == 1)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "[1]");
		}
		else if (lcdScreen == 2 && Program != 2)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "2");
			if (nLCDButtons == centerButton)
			{
				Program = lcdScreen;
				displayLCDCenteredString (0, "Twenty Point");
				displayLCDCenteredString (1, "Selected");
				wait1Msec(1500);
			}
		}
		else if (lcdScreen == 2 && Program == 2)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "[2]");
		}
		else if (lcdScreen == 3 && Program != 3)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "3");
			if (nLCDButtons == centerButton)
			{
				Program = lcdScreen;
				displayLCDCenteredString (0, "Stay Put");
				displayLCDCenteredString (1, "Selected");
				wait1Msec(1500);
			}
		}
		else if (lcdScreen == 3 && Program == 3)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "[3]");
		}
		else if (lcdScreen == 4 && Program != 4)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "4");
			if (nLCDButtons == centerButton)
			{
				Program = lcdScreen;
				displayLCDCenteredString (0, "tf do i put here");
				displayLCDCenteredString (1, "bottom text");
				wait1Msec(1500);
			}
		}
		else if (lcdScreen == 4 && Program == 4)
		{
			displayLCDCenteredString (0, "Program");
			displayLCDCenteredString (1, "[4]");
		}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void driveControlA(int rightDrive, int leftDrive)
{
	motor[leftSideDrive] = leftDrive;
	motor[rightSideDrive] = rightDrive;
}
void mogoControlA(int rightMogo, int leftMogo)
{
	motor[leftMobileGoal] = leftMogo;
	motor[rightMobileGoal] = rightMogo;
}
void tipperControlA(int rightTip, int leftTip)
{
	motor[leftTipper] = leftTip;
	motor[rightTipper] = rightTip;
	//nice
}

task autonomous()

{
	if(Program == 1)
	{
		driveControlA(127, 127);
		wait1Msec(3000);

		mogoControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(500);

		mogoControlA(127, 127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(1000);

		driveControlA(127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(1000);

		mogoControlA(-127, -127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, -127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(500);

		tipperControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(1000);

		//Placeholder for 10 point autonomous and tipper;
		//Disregard for now.

	}
	else if(Program == 2)
	{
		//Will Cam's old 20pt work?

		/*

		driveControlA(127, 127);
		wait1Msec(3000);

		mogoControlA(-127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(500);

		mogoControlA(127, 127);
		wait1Msec(500);

		driveControlA(-127, -127);
		wait1Msec(1000);

		driveControlA(127, -127);
		wait1Msec(500);

		driveControlA(127, 127);
		wait1Msec(1000);

		driveControlA(127, 127);
		wait1Msec(1000);

		*/

		//Placeholder for 20 point autonomous;
		//Disregard for now.
	}
	else if(Program == 3)
	{
		driveControlA(0, 0);
		mogoControlA(0, 0);
		tipperControlA(0, 0);
		wait1Msec(15000);
		/*
		hey guys minecraftman4876 coming atcha with a new video.
		today were gonna try and upgrade our iron tools to diamond,
		and hopefully get some obsidian so we can make our way to the nether.
		*/
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void mogoControlR(int rightMogo, int leftMogo)
{
	motor[leftMobileGoal] = leftMogo;
	motor[rightMobileGoal] = rightMogo;
}
void tipperControlR(int rightTip, int leftTip)
{
	motor[leftTipper] = leftTip;
	motor[rightTipper] = rightTip;
	//nice
}

task usercontrol()
{
	while(1==1)
	{
		motor[leftSideDrive] = vexRT[Ch3];
		motor[rightSideDrive] = vexRT[Ch2];

		if(vexRT[Btn6U] == 1)
		{
			mogoControlR(-127, -127);
		}
		else if(vexRT[Btn6D] == 1)
		{
			mogoControlR(127, 127);
		}
		else
		{
			mogoControlR(0, 0);
		}
		if(vexRT[Btn5D] == 1)
		{
			tipperControlR(-127, -127);
		}
		else if(vexRT[Btn5U] == 1)
		{
			tipperControlR(127, 127);
		}
		else
		{
			tipperControlR(0, 0);
		}
	}
}
