#pragma config(Sensor, in1,    LeftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in3,    RightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMobileGoal, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTipper,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftSideDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftTipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMobileGoal, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void liftControl(int leftspeed, int rightspeed)
{
motor[leftMobileGoal] = leftspeed;
motor[rightMobileGoal] = rightspeed;
}

void tipControl(int leftTip, int rightTip)
{
	 motor[leftTipper] = leftTip;
	motor[rightTipper] = rightTip;
}

		task MogoUp
		{
			liftControl(-127, -127);
			untilPotentiometerLessThan(560, in3);
		}

		task MogoDown
		{
		liftControl(127, 127);
		untilPotentiometerGreaterThan(1740, in3);
		}

		task tipUp
		{
			tipControl(-63, -63);
			wait1Msec(1000);
		}

		task tipDown
		{
			tipControl(63, 63);
			wait1Msec(1000);
		}

task main()
{
	while (1 == 1)
	{
		if(vexRT[Btn5U] == 1)
		{
			stopTask(tipDown);
			startTask(tipUp);
	}
	else if(vexRT[Btn5D] == 1)
	{
		stopTask(tipUp);
		startTask(tipDown);
	}
	else
	{
		tipControl(0, 0);
	}
	if(vexRT[Btn6U] == 1)
	{
		stopTask(MogoDown);
		startTask(MogoUp);
	}
	else if(vexRT[Btn6D] == 1)
	{
		stopTask(MogoUp);
		startTask(MogoDown);
	}
	else
	{
		liftControl(0, 0);
	}
}
}
