#pragma config(Motor,  port2,           rightSideDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftSideDrive, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int orientationStatus;

task Forwards()
{
	orientationStatus = 1;

	while(1==1)
	{
		motor[leftSideDrive] = vexRT[Ch3];
		motor[rightSideDrive] = vexRT[Ch2];
	}
}

task Reverse()
{
	orientationStatus = 0;

	while(1==1)
	{
		motor[leftSideDrive] = -vexRT[Ch3];
		motor[rightSideDrive] = -vexRT[Ch2];
	}
}

task main()
{
	startTask(Forwards);

	while(1==1)
	{

		while(orientationStatus == 1)
		{
			if(vexRT[Btn8U] == 1)
			{
				while(1==1)
			{
				stopTask(Forwards);
				startTask(Reverse);
				orientationStatus = 0;
			}
			}

			while(orientationStatus == 0)
			{
				if(vexRT[Btn8U] == 1)
				{
					while(1==1)
				{
					stopTask(Reverse);
					startTask(Forwards);
					orientationStatus = 1;
				}
				}
			}
		}
	}
}
